# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_pin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.ImageField(upload_to='static/img/pins'),
        ),
    ]
